"""empty message

Revision ID: c9d20ef823bd
Revises: 8903f49179c9
Create Date: 2022-02-03 13:56:08.062947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9d20ef823bd'
down_revision = '8903f49179c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('despesas', sa.Column('categoria', sa.String(length=200), nullable=True))
    op.drop_column('receitas', 'categoria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receitas', sa.Column('categoria', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('despesas', 'categoria')
    # ### end Alembic commands ###
