"""add categoria

Revision ID: d97bd4fa1858
Revises: bfd963d32476
Create Date: 2022-02-03 10:12:47.259801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97bd4fa1858'
down_revision = 'bfd963d32476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receitas', sa.Column('categoria', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receitas', 'categoria')
    # ### end Alembic commands ###
