"""empty message

Revision ID: ef065f045199
Revises: d975a6cbccbe
Create Date: 2022-02-05 15:06:12.442143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef065f045199'
down_revision = 'd975a6cbccbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nome', sa.String(length=200), nullable=False))
    op.add_column('user', sa.Column('senha', sa.String(length=200), nullable=False))
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('user', 'senha')
    op.drop_column('user', 'nome')
    # ### end Alembic commands ###
